name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_linux:
    name: Build Slackbot for Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    
    - name: Test
      run: make test

    - name: Build
      run: make build_linux

    - name: Upload a Linux Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: slackbot_amd64_linux
        path: /home/runner/work/slackbot/slackbot/bin/linux/slackbot

  build_mac:
    name: Build Slackbot for MacOS
    runs-on: macos-11.0
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: make test

      - name: Build
        run: make build_mac

      - name: Upload a MacOS Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: slackbot_amd64_darwin
          path: /Users/runner/work/slackbot/slackbot/bin/macos/slackbot